# Generated by Django 5.2.9 on 2026-01-15 18:25

from django.db import migrations

def is_new_building(apps,schema_editor):

    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if flat.construction_year>=2015:
            flat.new_building=True
        else: 
            flat.new_building=False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(is_new_building)
    ]

