# Generated by Django 5.2.9 on 2026-01-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_likes_flat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='user',
        ),
    ]
