# Generated by Django 5.2.9 on 2026-02-03 17:16

from django.db import migrations
import phonenumbers

def convert_to_pure_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(owners_phonenumber='+70000000000'):
        if not flat.owners_phonenumber:
            continue
        try:
            parse_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except NumberParseException as e:
            print(f'Неверный формат номера у квартиры {flat.id}')
            print(f'Ошибка {e}')
            continue

        flat.owner_pure_phone = phonenumbers.format_number(parse_phone, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_likes'),
    ]

    operations = [
    migrations.RunPython(convert_to_pure_phonenumbers)
    ]


