# Generated by Django 5.2.9 on 2026-02-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_flat_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
